# Generated by Django 4.2.17 on 2024-12-27 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_rename_creator_coment_creater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='liking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liker', to='post.post'),
        ),
    ]
