# Generated by Django 4.2.17 on 2024-12-27 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_like_liking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='liking',
        ),
        migrations.AddField(
            model_name='like',
            name='post',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='post_like', to='post.post'),
            preserve_default=False,
        ),
    ]
