# Generated by Django 4.2.17 on 2024-12-27 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_like_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='liker',
            new_name='creater',
        ),
    ]
